### ISSUE TITLE
Random Timer Duplication

### ISSUE THREAD

**Issue by BlythMeister** [BlythMeister/Gallifrey#125]
When waking up the PC after a 20 min. break with timer running, Gallifrey was showing the running timers task on four rows. One running and two with different time values. The fourth was a duplication of the third row.

Stack trace:

System.NullReferenceException: Objektreferanse er ikke satt til en objektforekomst.
at System.Windows.Forms.ListBox.NativeUpdateSelection
at System.Windows.Forms.ListBox.SelectedObjectCollection.EnsureUpToDate
at System.Windows.Forms.ListBox.SelectedObjectCollection.get_InnerArray
at System.Windows.Forms.ListBox.get_SelectedItem
at Gallifrey.UI.Classic.MainWindow.GetSelectedTimer in f:\GIT\Gallifrey\src\Gallifrey.UI.Classic\MainWindow.cs:line 974:col 25
at Gallifrey.UI.Classic.MainWindow.SetDisplayClock in f:\GIT\Gallifrey\src\Gallifrey.UI.Classic\MainWindow.cs:line 873:col 13
at Gallifrey.UI.Classic.MainWindow.formTimer_Tick(System.Object sender, System.EventArgs e) in f:\GIT\Gallifrey\src\Gallifrey.UI.Classic\MainWindow.cs:line 276:col 13
at System.Windows.Forms.Timer.OnTick(System.EventArgs e)
at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(System.Windows.Forms.Message& m)
at System.Windows.Forms.NativeWindow.Callback(System.IntPtr hWnd, System.Int32 msg, System.IntPtr wparam, System.IntPtr lparam)

**Comment by BlythMeister** [comment]
Potential work around to handle that error and  do a complete redraw of the list. 
It would seem timers which don't exist show in the list.

**Comment by BlythMeister** [comment]
Issue fixed for v2.2.0
Closing
