### ISSUE TITLE
Serialize Exception

### ISSUE THREAD

**Issue by BlythMeister** [BlythMeister/Gallifrey#149]
Gallifrey.Exceptions.Serialization.SerializerError: Error in serialization
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\bruce.keen\AppData\Roaming\Gallifrey\TimerCollection.dat' because it is being used by another process.
at System.IO.__Error.WinIOError()
at System.IO.FileStream.Init()
at System.IO.FileStream..ctor()
at System.IO.StreamWriter.CreateFile()
at System.IO.StreamWriter..ctor()
at System.IO.File.InternalWriteAllText()
at System.IO.File.WriteAllText()
at Gallifrey.Serialization.ItemSerializer`1.Serialize() in f:\GIT\Gallifrey\src\Gallifrey\Serialization\ItemSerializer.cs:line 41:col 13
--- End of inner exception stack trace ---
at Gallifrey.Serialization.ItemSerializer`1.Serialize(Gallifrey.Serialization.T obj) at offset 60 in f:\GIT\Gallifrey\src\Gallifrey\Serialization\ItemSerializer.cs:line 49:col 17
at Gallifrey.Serialization.JiraTimerCollectionSerializer.Serialize(System.Collections.Generic.List`1 timerCollection) at offset 22 in f:\GIT\Gallifrey\src\Gallifrey\Serialization\JiraTimerCollectionSerializer.cs:line 17:col 13
at Gallifrey.JiraTimers.JiraTimerCollection.RefreshFromJira(System.Guid uniqueId, Gallifrey.Jira.Model.Issue jiraIssue, Gallifrey.Jira.Model.User currentUser) at offset 16 in f:\GIT\Gallifrey\src\Gallifrey\JiraTimers\JiraTimerCollection.cs:line 293:col 13
at Gallifrey.UI.Classic.ExportTimerWindow..ctor(Gallifrey.IBackend gallifrey, System.Guid timerGuid) at offset 212 in f:\GIT\Gallifrey\src\Gallifrey.UI.Classic\ExportTimerWindow.cs:line 40:col 17
at Gallifrey.UI.Classic.MainWindow.btnExport_Click(System.Object sender, System.EventArgs e) at offset 23 in f:\GIT\Gallifrey\src\Gallifrey.UI.Classic\MainWindow.cs:line 481:col 13
at Gallifrey.UI.Classic.MainWindow.MainWindow_KeyUp(System.Object sender, System.Windows.Forms.KeyEventArgs e) at offset 228 in f:\GIT\Gallifrey\src\Gallifrey.UI.Classic\MainWindow.cs:line 172:col 25
at System.Windows.Forms.Control.OnKeyUp(System.Windows.Forms.KeyEventArgs e) at offset 25
at System.Windows.Forms.Control.ProcessKeyEventArgs(System.Windows.Forms.Message& m) at offset 711
at System.Windows.Forms.Form.ProcessKeyPreview(System.Windows.Forms.Message& m) at offset 18
at System.Windows.Forms.TabControl.ProcessKeyPreview(System.Windows.Forms.Message& m) at offset 11
at System.Windows.Forms.Control.ProcessKeyPreview(System.Windows.Forms.Message& m) at offset 8
at System.Windows.Forms.Control.ProcessKeyMessage(System.Windows.Forms.Message& m) at offset 8
at System.Windows.Forms.Control.WmKeyChar(System.Windows.Forms.Message& m) at offset 0
at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message& m) at offset 1583
at System.Windows.Forms.ListBox.WndProc(System.Windows.Forms.Message& m) at offset 654
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(System.Windows.Forms.Message& m) at offset 0
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(System.Windows.Forms.Message& m) at offset 142
at System.Windows.Forms.NativeWindow.Callback(System.IntPtr hWnd, System.Int32 msg, System.IntPtr wparam, System.IntPtr lparam) at offset 37

**Comment by BlythMeister** [comment]
Added a retry (3 times) into serialization which should prevent this.
